services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: kunlaquota
      POSTGRES_USER: kunla
      POSTGRES_PASSWORD: quota
    ports:
      - "5432:5432"
  kunlaquota:
    image: docker.io/library/kunlaquota:0.0.1-SNAPSHOT
    platform: linux/amd64
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kunlaquota
      SPRING_DATASOURCE_USER: kunla
      SPRING_DATASOURCE_PASSWORD: quota
    ports:
      - "9999:8080"